name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt-openjdk'

    - name: Build with Maven
      run: mvn clean package

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Deploy to Elastic Beanstalk
      run: |
        zip -r backend-app.zip target/*.jar
        aws elasticbeanstalk create-application-version --application-name your-app-name --version-label ${{ github.sha }} --source-bundle S3Bucket=your-bucket-name,S3Key=backend-app.zip
        aws elasticbeanstalk update-environment --application-name your-app-name --environment-name your-env-name --version-label ${{ github.sha }}

