name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build backend
      working-directory: ./ecommerce-backend
      run: ./mvnw clean install

    - name: Build frontend
      working-directory: ./ecommerce-frontend
      run: npm install && npm run build

    - name: Run tests
      run: |
        cd ./ecommerce-backend
        ./mvnw test
        cd ../ecommerce-frontend
        npm test

    - name: Deploy to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        aws s3 sync ./ecommerce-frontend/build s3://your-bucket-name/frontend
        aws deploy push --application-name your-app-name --s3-location s3://your-bucket-name/backend.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

